### ISSUE TITLE
y3Wasm file source ?

### ISSUE THREAD

**Issue by gedw99** [yomorun/yomo-presence-backend#14]
Yomo is crazy awesome btw.

https://github.com/yomorun/presencejs/blob/main/src/helper.ts#L4 shows that wasm is used as a dependecy.
I am playing around with the code and want to change this code.
I cant seems to find where y3Wasm is compiled from. There is no client in https://github.com/yomorun/yomo-presence-backend.  Would love it if someone can let me know.

**Comment by gedw99** [comment]
I want to build the gui using golang and so need to compile to wasm

**Comment by fanweixiao** [comment]
@gedw99, `y3Wasm` is just a wire-codec, if you want to putting your golang code to web browser, you can take a look at [WasmEdge](https://www.cncf.io/projects/wasmedge-runtime/) or [Wasmtime](https://wasmtime.dev/)

**Comment by gedw99** [comment]
https://github.com/yomorun/y3 Is the “ wire format “ that you refer to I suspect

**Comment by gedw99** [comment]
Open source but not the wire format ??
